name: echo
description: echo message

inputs:
  message:
    description: 'Message to echo'
    required: true

runs:
  using: "composite"
  steps:
    - name: echo
      run: echo "${{ inputs.message }}"
      shell: bash
